name: CI - Test, Build, Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Trigger deploy hook and wait for completion
        env:
          VERCEL_DEPLOY_HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          echo "Triggering Vercel deploy hook..."
          response=$(curl -s -w "%{http_code}" -X POST "$VERCEL_DEPLOY_HOOK_URL")
          http_code="${response: -3}"
          body="${response:0:${#response}-3}"

          if [ "$http_code" != "201" ]; then
            echo "Failed to trigger deploy hook, HTTP code: $http_code"
            echo "Response body: $body"
            exit 1
          fi

          job_id=$(echo "$body" | jq -r '.job.id')
          echo "Deploy job ID: $job_id"

          echo "Waiting for deploy to complete..."
          while true; do
            sleep 5
            status_response=$(curl -s -H "Authorization: Bearer $VERCEL_TOKEN" "https://api.vercel.com/v6/deployments/${job_id}")
            state=$(echo "$status_response" | jq -r '.state')
            echo "Deploy status: $state"

            if [[ "$state" == "READY" ]]; then
              echo "Deploy succeeded!"
              exit 0
            elif [[ "$state" == "ERROR" ]]; then
              echo "Deploy failed!"
              exit 1
            fi
          done
