name: CI - Test, Build, Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Call Vercel Deploy Hook
        id: vercel_deploy
        run: |
          response=$(curl -s -w "%{http_code}" -X POST ${{ secrets.VERCEL_DEPLOY_HOOK_URL }})
          body=${response::-3}
          code=${response: -3}
          echo "Response code: $code"
          echo "Response body: $body"
          if [ "$code" = "200" ] || [ "$code" = "201" ]; then
            echo "✅ Deploy hook triggered successfully!"
          else
            echo "❌ Failed to trigger deploy hook"
            exit 1
          fi
